### PR TITLE
feat: added support to java driver 4.0

### PR DESCRIPTION
**Pull request by emas80**
I have opened this

https://jira.mongodb.org/browse/JAVA-3873?filter=-2

The way we are going to use this library is like this
https://github.com/faceit/microservice-java-mongodb/pull/33

I will clean up all the imports etc on the other projects

### CODE REVIEW

**Comment by faceitdev** [comment]
Version: `f3e3cfef1fc078-SNAPSHOT`

**Comment by faceitdev** [comment]
Version: `d74fb8f1e7c253-SNAPSHOT`

**Comment by faceitdev** [comment]
Version: `d22dd1c0673297-SNAPSHOT`

**Comment by faceitdev** [comment]
Version: `050a22ee44bb3c-SNAPSHOT`

**Comment by faceitdev** [comment]
Version: `050a22ee44bb3c-SNAPSHOT`

**Comment by faceitdev** [comment]
Version: `0241346ef6b4ff-SNAPSHOT`

**Comment by faceitdev** [comment]
Version: `b5c29a87a070a1-SNAPSHOT`

**Comment by faceitdev** [comment]
Version: `d8262332decb0f-SNAPSHOT`

**Comment by faceitdev** [comment]
Version: `980644e5e90399-SNAPSHOT`

**Comment by tftdias** [comment]
the issue link doesn't seem to be correct, can you double check @emas80?

**Review by tftdias — APPROVED** [review]
lgtm. one thing though, it's common for your PRs to change code format/indentation quite a lot making the review process a bit difficult sometimes, especially because git(hub) is not smart enough identifying the actual changes.

**Comment by emas80** [comment]
If I click on the links, I can correctly open the page from MongoDb and from github..

@tftdias the format was actually "wrong", as the original project is using 2 chars instead of 4 for the tab. Saving the file has changed the entire file.

**Pull request merged**
